### PR TITLE
Update README with script include instructions

### PR DESCRIPTION
**Pull request by benwiley4000**
I'd also propose that you update GitHub releases with copies of the dist file.

Thanks! 🙂

### CODE REVIEW

**Comment by vaneenige** [comment]
Hey Ben,

I'll include copies of the dist file with every release. For now I'll leave the README as is, but I might add a different way of including the library later, stay tuned!

**Comment by benwiley4000** [comment]
Hey @vaneenige - up to you! When I shared this library with some game developers they complained that they have to be using a JS bundler to use it. When I showed them they could just use unpkg they were pretty happy about that! :) Any instructions on script inclusion in the readme would be well received I think. :)

**Comment by vaneenige** [comment]
Fair enough! I've added a small reference to _unpkg_ (for script tags / modules)! See 76f0f8d0169c4ea754da8dcdba0fb92799c15dfc.

Thanks! 🙌

**Comment by benwiley4000** [comment]
Cool!

**Pull request closed without merging**
